# 3.1.2 n개의 주식 포트폴리오 기대수익률

In [1]:
import numpy as np

# 자산의 개수를 정한다. 자산의 개수는 난수를 만들 때 사용할 것이다
numStocks = 3

# 세 가지 경기 국면별로 자산의 개수만큼 주식의 수익률을 난수로 생성한다
# [3 x numStocks] 배열을 만들고 만들어진 수익률 배열을 출력한다
returns = np.random.randn( 3, numStocks )
print( '1. 난수로 만드는 국면별 주식의 수익률: \n', returns )

# 세 가지 경기 국면별 확률을 만든다. 이것 역시 난수로 만든다
# 세 가지 국면의 확률의 전체 합이 1.0이 되도록 한다
# 난수를 세 개 만든다
prob = np.random.rand( 3 )

# 생성한 난수를 난수의 합계로 나눠 합이 1.0이 되도록 한다
prob = prob / prob.sum( )
print( '2. 경기 국면별 각 확률: \n', prob )

# 경기 국면별 확률과 수익률을 행렬 곱셈한다. 연산의 결과 각 주식의 기대수익률이 계산된다
# 경기 국면별 확률과 수익률을 곱한다
expectedReturns = np.matmul( prob.T, returns )

# prob.T는 prob 전치행렬이며 두 행렬의 곱은 * 또는 matmul( ) 함수를 사용할 수 있다
expectedReturns = prob.T * returns
print( '3. 각 주식의 기대수익률: \n', expectedReturns )

# 투자 비중을 만든다. 주식의 개수(numStocks)대로 난수를 만든 후 이를 난수의 합으로 다시 나눠 전체 투자 비중의 합(100%)이 1.0이 되도록 한다
weights = np.random.rand( numStocks )
weights = weights / weights.sum( )
print( '4. 투자 비중*기대수익률: \n', weights )

# 각각의 투자 비중과 주식 기대수익률의 곱을 모두 합해 포트폴리오의 기대수익률을 계산한다
expectedReturnOfPortfolio = np.sum( weights*expectedReturns )
print( '5. 포트폴리오의 기대수익률: {:.2%}'.format( expectedReturnOfPortfolio ) )

1. 난수로 만드는 국면별 주식의 수익률: 
 [[-1.82053732 -1.21837077 -0.59420168]
 [-0.53795177 -0.12127415  0.02154268]
 [ 0.29622298  0.08865775 -0.63159411]]
2. 경기 국면별 각 확률: 
 [0.40703978 0.14217859 0.45078163]
3. 각 주식의 기대수익률: 
 [[-0.74103111 -0.17322623 -0.2678552 ]
 [-0.21896777 -0.01724259  0.00971105]
 [ 0.12057454  0.01260523 -0.28471102]]
4. 투자 비중*기대수익률: 
 [0.2358378  0.42548025 0.33868195]
5. 포트폴리오의 기대수익률: -45.75%


## Pandas를 이용해 실제 데이터로 포트폴리오의 기대수익률 계산



In [8]:
!pip install yfinance

     |████████████████████████████████| 6.3 MB 7.5 MB/s 
  Created wheel for yfinance: filename=yfinance-0.1.64-py2.py3-none-any.whl size=24109 sha256=4bf22e684cfc096de1a3413d07b7e8dc06c41e51498f1275323a058f15cf9395
  Stored in directory: /root/.cache/pip/wheels/86/fe/9b/a4d3d78796b699e37065e5b6c27b75cff448ddb8b24943c288
Successfully built yfinance
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6


In [25]:
import numpy as np
import pandas as pd
from pandas_datareader import data as pdr
import random
import datetime
import yfinance as yf
yf.pdr_override()

tickers = ['MMM', 'ADBE', 'AMD', 'GOOGL', 'GOOG', 'AMZN']

adjClose = pd.DataFrame()

for item in tickers:
# Yahoo Finance에서 시작일과 종료일 사이의 지정된 기간 동안 주식 데이터 가져 오기
  adjClose[item] = pdr.get_data_yahoo(tickers=item, start="2020-09-15", end="2021-09-15")['Adj Close']

dailySimpleReturns = adjClose.pct_change()

meanReturns = np.matrix(dailySimpleReturns.mean())

numAssets = len(tickers)

weights = np.random.random(numAssets)
weights = weights / sum(weights)

portReturnsExpected = np.sum(weights * meanReturns.T)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [26]:
meanReturns

matrix([[0.00056963, 0.00117465, 0.00146978, 0.00259757, 0.00259978,
         0.00050567]])

In [29]:
portReturnsExpected

0.0014741320843037796

In [37]:
# n개 주식 포트폴리오의 분산을 계산하는 코드

tickers = [ 'MMM', 'ADBE', 'AMD', 'GOOGL', 'GOOG', 'AMZN' ]
adjClose = pd.DataFrame( )

for item in tickers:
    adjClose[ item ] = pdr.get_data_yahoo(tickers=item, start="2020-09-15", end="2021-09-15")['Adj Close']
dailySimpleReturns = adjClose.pct_change( )

# 행렬 연산을 위해 weights를 matrix 데이터형으로 변환한다
weights = np.matrix( weights )

print( 'dailySimpleReturns의 데이터형: ', type( dailySimpleReturns ) )
print( 'dailySimpleReturns.cov() 결과의 데이터형: ', type( dailySimpleReturns.cov()) )

pcov = dailySimpleReturns.cov().values

varp = weights*pcov*weights.T
print('포트폴리오 분산:', varp)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
dailySimpleReturns의 데이터형:  <class 'pandas.core.frame.DataFrame'>
dailySimpleReturns.cov() 결과의 데이터형:  <class 'pandas.core.frame.DataFrame'>
포트폴리오 분산: [[0.00014567]]


dailySimpleReturns.cov() 결과의 데이터형:  <class 'pandas.core.frame.DataFrame'>
